FROM node:8-alpine as builder

WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/
RUN npm install --only=production --silent

COPY public public/
COPY src src/

RUN npm run build

## 2nd stage

FROM nginx:1.13.6-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/build /usr/share/nginx/html/
COPY --from=builder /usr/src/app/build/index.html /usr/share/nginx/index-template.html

COPY nginx-entrypoint.sh /

ENTRYPOINT ["sh", "/nginx-entrypoint.sh"]

CMD ["nginx"]
