FROM node:8-alpine as builder

WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/
RUN yarn install --non-interactive --pure-lockfile

COPY . /usr/src/app

RUN CI=true yarn test
RUN yarn build

## 2nd stage

FROM nginx:1.13-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
